import React, { useState } from 'react'
import { FaDownload, FaFilePdf, FaFileCsv } from 'react-icons/fa'

export default function ExportBuild({ build, onClose }) {
  const [exportType, setExportType] = useState('pdf')
  const [isExporting, setIsExporting] = useState(false)

  const handleExport = async () => {
    setIsExporting(true)
    
    // Implement actual export logic FR13
    const exportData = {
      buildName: build.name || `PC Build - ${new Date().toLocaleDateString()}`,
      budget: build.budget,
      totalPrice: build.items.reduce((sum, item) => sum + item.price, 0),
      performance: build.optimal,
      components: build.items,
      timestamp: new Date().toISOString()
    }

    if (exportType === 'csv') {
      exportToCSV(exportData)
    } else {
      exportToPDF(exportData)
    }

    setTimeout(() => {
      setIsExporting(false)
      onClose()
    }, 2000)
  }

  const exportToCSV = (data) => {
    const csvContent = [
      // Header row
      ['Component Type', 'Name', 'Price', 'Link'],
      // Data rows
      ...data.components.map(item => [
        item.category,
        item.name,
        `$${item.price}`,
        item.link
      ]),
      // Summary rows
      ['', '', '', ''],
      ['Total Price:', '', `$${data.totalPrice}`, ''],
      ['Budget:', '', `$${data.budget}`, ''],
      ['Performance Score:', '', `${data.performance}%`, '']
    ].map(row => row.join(',')).join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${data.buildName.replace(/[^a-z0-9]/gi, '_')}.csv`
    link.click()
    window.URL.revokeObjectURL(url)
  }

  const exportToPDF = (data) => {
    // TODO: Implement PDF export with a library like jsPDF
    // For now, create a simple HTML export that can be printed as PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${data.buildName}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          .header { text-align: center; margin-bottom: 30px; }
          .summary { background: #f5f5f5; padding: 15px; margin-bottom: 20px; }
          .components { margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #a259ff; color: white; }
          .footer { margin-top: 30px; text-align: center; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${data.buildName}</h1>
          <p>Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div class="summary">
          <h2>Build Summary</h2>
          <p><strong>Budget:</strong> $${data.budget}</p>
          <p><strong>Total Price:</strong> $${data.totalPrice}</p>
          <p><strong>Performance Score:</strong> ${data.performance}%</p>
          <p><strong>Budget Utilization:</strong> ${((data.totalPrice / data.budget) * 100).toFixed(1)}%</p>
        </div>
        
        <div class="components">
          <h2>Components</h2>
          <table>
            <thead>
              <tr>
                <th>Component Type</th>
                <th>Name</th>
                <th>Price</th>
                <th>Vendor Link</th>
              </tr>
            </thead>
            <tbody>
              ${data.components.map(item => `
                <tr>
                  <td>${item.category}</td>
                  <td>${item.name}</td>
                  <td>$${item.price}</td>
                  <td><a href="${item.link}" target="_blank">View Product</a></td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="footer">
          <p>Generated by PC Build Generator</p>
          <p>Visit us at pcbuildgenerator.com for more builds</p>
        </div>
      </body>
      </html>
    `

    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${data.buildName.replace(/[^a-z0-9]/gi, '_')}.html`
    link.click()
    window.URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-md flex items-center justify-center z-50 p-4">
      <div className="relative w-full max-w-md overflow-hidden rounded-3xl border border-white/15 bg-card-elevated/95 px-6 py-8 shadow-2xl">
        <div className="absolute -right-16 -top-20 h-40 w-40 rounded-full bg-gradient-to-br from-primary/30 to-secondary/30 blur-3xl opacity-60" />
        <div className="relative">
          <h3 className="text-2xl font-bold text-white mb-4">Export Build</h3>
          
          <div className="space-y-4 mb-6">
            <div>
              <label className="block text-sm font-medium text-white/80 mb-2">Export Format</label>
              <div className="space-y-3">
                <label className={`flex items-center gap-3 rounded-2xl border px-4 py-3 cursor-pointer transition-colors duration-200 ${
                  exportType === 'pdf' ? 'border-secondary/60 bg-white/10' : 'border-white/10 bg-white/5 hover:bg-white/10'
                }`}>
                  <input
                    type="radio"
                    name="exportType"
                    value="pdf"
                    checked={exportType === 'pdf'}
                    onChange={(e) => setExportType(e.target.value)}
                    className="text-secondary focus:ring-secondary"
                  />
                  <FaFilePdf className="text-secondary" />
                  <span className="text-white">PDF Document</span>
                </label>
                
                <label className={`flex items-center gap-3 rounded-2xl border px-4 py-3 cursor-pointer transition-colors duration-200 ${
                  exportType === 'csv' ? 'border-secondary/60 bg-white/10' : 'border-white/10 bg-white/5 hover:bg-white/10'
                }`}>
                  <input
                    type="radio"
                    name="exportType"
                    value="csv"
                    checked={exportType === 'csv'}
                    onChange={(e) => setExportType(e.target.value)}
                    className="text-secondary focus:ring-secondary"
                  />
                  <FaFileCsv className="text-emerald-400" />
                  <span className="text-white">CSV Spreadsheet</span>
                </label>
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
              <p className="text-text-sub text-sm">
                {exportType === 'pdf' 
                  ? 'Generate a polished HTML export ready to print or save as PDF.'
                  : 'Download structured data for spreadsheets and price comparisons.'
                }
              </p>
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="flex-1 inline-flex items-center justify-center gap-2 rounded-2xl bg-primary text-white font-semibold py-3 px-4 transition-all duration-200 shadow-glow hover:bg-primary/90 hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isExporting ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  Exporting...
                </>
              ) : (
                <>
                  <FaDownload />
                  Export {exportType.toUpperCase()}
                </>
              )}
            </button>
            
            <button
              onClick={onClose}
              className="px-4 py-3 rounded-2xl border border-white/10 text-text-sub hover:text-white hover:bg-white/10 transition-colors duration-200"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
